modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
[[mods]]
modId="crittersandcompanions"
version="${file.jarVersion}"
displayName="{Warped} Critters and Companions"
logoFile="logo.png"
authors="Joosh, EterDelta"
description='''
Critters and Companions is a vanilla-style creature mod which fills the overworld with new animals.
!Warped Version!
This is not an official version of Critters and Companions, please report all issues to the Warped-Modding repo.
'''

[[dependencies.crittersandcompanions]]
    modId="geckolib3"
    mandatory=true
    versionRange="[3.0.27,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.crittersandcompanions]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.crittersandcompanions]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
